# Generated by Django 5.2 on 2025-05-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageURL',
            new_name='imageUrl',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Surfboards', 'Surfboards'), ('Skimboards', 'Skimboards')], max_length=20),
        ),
    ]
