# Generated by Django 5.2 on 2025-05-05 20:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_order_shippingmethod_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cogs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
